apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: node
        name: backend
        ports:
        - containerPort: 3000
      restartPolicy: Always
status: {}
