apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-opnv-frontend
  name: ms-opnv-frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: ms-opnv-frontend
status:
  loadBalancer: {}
